config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"

  resources :relationships
  resources :rooms do
    member do
      resource :exames
      post 'start', to: "exames#start_game"
      get 'result', to: "exames#result"
      get :unfollow
    end
    resource :answers
  end
end

app/models/answser.rb
class Answser < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_room.rb
class ClassRoom < ApplicationRecord
  has_many :class_room_subjects
  has_many :subjects, through: :class_room_subjects, dependent: :destroy
end

app/models/class_room_subject.rb
class ClassRoomSubject < ApplicationRecord
  belongs_to :class_room
  belongs_to :subject
end

app/models/exame.rb
class Exame < ApplicationRecord
  has_many :exame_questions
  has_many :questions, through: :exame_questions
end

app/models/exame_question.rb
class ExameQuestion < ApplicationRecord
  belongs_to :exame
  belongs_to :question
end

app/models/notification.rb
class Notification < ApplicationRecord

  after_create_commit :send_notification

  private

  def send_notification
    user = User.find_by id: self.sender_id

    member_html = ApplicationController.renderer.render partial: "public_activity/member_room", locals: {user: user}

    if self.checked == true
      # user dang o trong phong va an nut san sang
      if self.ready == true
        ActionCable.server.broadcast "room_#{self.receiver_id}_channel", checked: true, ready: true, user_id: self.sender_id
      # user dang o trong phong va an nut san sang
      elsif self.ready ==  false
        ActionCable.server.broadcast "room_#{self.receiver_id}_channel", checked: true, ready: false
      else
      # khi user bat dau join phong
        ActionCable.server.broadcast "room_#{self.receiver_id}_channel", content: member_html, checked: true
      end
    else
      # khi user bat dau roi phong
      ActionCable.server.broadcast "room_#{self.receiver_id}_channel", checked: false, user_id: self.sender_id
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :exame_questions
  has_many :exames, through: :exame_questions
  has_many :answers, :foreign_key => "question_id", :class_name => "Answser", dependent: :destroy

  scope :get_questions, ->subject_id, class_room_id do
    where subject_id: subject_id, class_room_id: class_room_id
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Room"
  belongs_to :followed, class_name: "User"
  after_save :make_notification_when_in_room_or_join_room
  after_destroy :make_notification_leave_room

  scope :created_sort, ->{order created_at: :desc}
  scope :is_not_start, -> room_id do
    (where follower_id: room_id, status: 0).count
  end

  private

  def make_notification_leave_room
    Room.find_by(id: self.follower_id).following.each do |user|
      Notification.create sender_id: self.followed_id, receiver_id: user.id, checked: false
    end
  end

  def make_notification_when_in_room_or_join_room
    if self.status == 1
      Room.find_by(id: self.follower_id).following.each do |user|
        Notification.create sender_id: self.followed_id, receiver_id: user.id, ready: true, checked: true
      end
    elsif self.status == 0
      Room.find_by(id: self.follower_id).following.each do |user|
        Notification.create sender_id: self.followed_id, receiver_id: user.id, ready: false, checked: true
      end
    else
      Room.find_by(id: self.follower_id).following.each do |user|
        Notification.create sender_id: self.followed_id, receiver_id: user.id, checked: true
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :users, through: :user_rooms

  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.destroy(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/score_provisional.rb
class ScoreProvisional < ApplicationRecord
  # after_update :make_notification

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :class_room_subjects
  has_many :class_rooms, through: :class_room_subjects, dependent: :destroy
  has_many :question, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :scores, dependent: :destroy
end

app/models/user_history.rb
class UserHistory < ApplicationRecord
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsHelper
  before_action :check_show_roo, only: :show
  before_action :make_exame, only: :create

  def index
    @rooms = Room.all
  end

  def show
    if get_relationship_id(current_user).status.nil?
      get_relationship_id(current_user).update status: 0
    end
  end

  def new
    if Relationship.pluck(:followed_id).include? current_user.id
      flash[:danger] = "Ban Dang Thi dau nen khong the tao phong."
      redirect_to root_path
    else
      @room = Room.new
    end
  end

  def create
    @room = current_user.rooms.new room_params.merge(exame_id: @exame.id)
    @room.owner = current_user.id
    if @room.save
      redirect_to @room
    else
      render :new
    end
  end

  def unfollow
    room = Room.find_by id: params[:id]
    if room.following? current_user
      room.unfollow current_user
      if current_user.id == room.owner && room.following.size > 1
        room.update_attributes owner: room.following.first.id
      end
      redirect_to root_path
    end
  end

  def destroy
    @room = Room.find_by id: params[:id]
    @room.destroy if @room.following.size == 1
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit :user_quantity, :class_room_id, :subject_id, :name
  end

  def check_show_roo
    @room = Room.find_by id: params[:id]
    return redirect_to root_path unless @room
    if (@room.following.size == @room.user_quantity) || (Relationship.pluck(:followed_id).include? current_user.id)
      return if @room.following? current_user
      flash[:danger] = "Phòng đã đủ người."
      redirect_to root_path
    else
      follow_room
    end
  end

  def follow_room
    if !@room.following? current_user
      @room.follow current_user
    end
  end

  def make_exame
    @exame = Exame.offset(rand(Exame.count)).last if Exame.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def owner_room id
    User.find_by(id: id).name if id
  end

  def kind_room quantity_room
    quantity_room == 1 ? "Doi Khang" : "Tap The"
  end

  def class_room_name id
    ClassRoom.find_by(id: id).name
  end

  def subject_name id
    Subject.find_by(id: id).name
  end

  def status_room room
    "#{room.following.size}/#{room.user_quantity}"
  end

  def get_relationship_id user
    Relationship.find_by followed_id: user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamOnline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag "favicon.ico" %>
  </head>

  <body>
    <% if user_signed_in? %>
    <%= render "shared/header" %>
    <%#= render "shared/create_room" %>
    <%#= render "shared/waiting_room" %>
    <%#= render "shared/in_room" %>
    <% end %>
      <%= yield %>
    <%#= render "shared/login_form" %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>

  </body>
</html>

app/views/public_activity/_member_room.html.erb
<div class="player" id= "user-<%= user.id %>">
  <div class="image-player">
    <%= image_tag "avatar.jpg" %>
  </div>
  <div class="text-center"><strong><%= user.name %></strong></div>
  <div class="user-win"><span>1996</span></div>
  <div class="text-center"><span>TRẬN THẮNG</span></div>
</div>

app/views/shared/_create_room.html.erb
<div class="header">
  <ul class="top-nav">
    <li class="logo-top-nav">
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-users">  Tìm phòng đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-graduation-cap">   Bảng xếp hạng</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-clock-o">   Lịch sử thi đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-book">   Hướng dẫn</i>
      <% end %>
    </li>
  </ul>
  <ul class="top-nav pull-right">
    <li class="user-avatar">
      <%= image_tag "avatar.jpg"%>
    </li>
    <li>Tran Duc Thang</li>
  </ul>
</div>

<div class="container">
  <div class="top-nav-content">
    <ul class="title-list-room">
      <li>TẠO PHÒNG THI ĐẤU</li>
      <li class="pull-right">
        <%= link_to root_path, class: "btn btn-primary" do %>
          <i class="fa fa-user-plus">Thi Đấu</i>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="content row">
    <div class="list-room">
      <div class="notice-new-room">
        <span>Tạo phòng đấu mới bằng cách chọn hình thức thi đấu và khẩu hiệu phòng (có thể bỏ qua)</span>
      </div>
      <div class="new-room">
        <div class="kind-room">
          <span>CHỌN HÌNH THỨC THI ĐẤU</span>
          <div class="kind_play">
            <input type="radio" name="kindroom">  Đối kháng (1 vs 1)<br>
           &nbsp;&nbsp; &nbsp;Đấu với 1 người chơi khác
          </div>
          <div class="kind_play">
            <input type="radio" name="kindroom">  Đấu tập thể (1 vs 9)<br>
           &nbsp;&nbsp;&nbsp; Đấu với 9 người chơi khác
          </div>
          <div class="row class-subject">
            <div class="form-group col-md-5">
              <select class="form-control" id="sel1">
                <option>Lớp</option>
                <option>Lớp 1</option>
                <option>Lớp 2</option>
                <option>Lớp 3</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <select class="form-control" id="sel1">
                <option>Toán lớp 1</option>
                <option>Tiếng việt lớp 1</option>
                <option>Tiếng Anh 1</option>
                <option>Tiếng Anh 2</option>
              </select>
            </div>
          </div>
          <div class="form-group lock-room">
            <input type="checkbox" name="">
            &nbsp;&nbsp;<span>Phòng thi đấu riêng</span>
            <i class="fa fa-lock" aria-hidden="true"></i>
          </div>
          <div class="footer-new-room">
            <div class="btn-new-room">
              <button class="btn btn-success">Tạo phòng</button>
            </div>
            <div class="btn-close-room">
              <button class="btn btn-danger">Thoát</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="chat">
      <div class="top-nav-chat">
        <span>Nhắn tin</span>
      </div>
      <div class="content-chat">

      </div>
      <div class="footer-chart">

      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
_footer.html.erb

app/views/shared/_header.html.erb
<div class="header">
  <ul class="top-nav">
    <li class="logo-top-nav">
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to rooms_path do %>
        <i class="fa fa-users">  Tìm phòng đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-graduation-cap">   Bảng xếp hạng</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-clock-o">   Lịch sử thi đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-book">   Hướng dẫn</i>
      <% end %>
    </li>
  </ul>
  <ul class="top-nav pull-right">
    <li class="user-avatar">
      <%= image_tag "avatar.jpg"%>
    </li>
    <li><%= current_user.name %></li>
  </ul>
</div>

app/views/shared/_in_room.html.erb
<div class="header">
  <ul class="top-nav">
    <li class="logo-top-nav">
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-users">  Tìm phòng đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-graduation-cap">   Bảng xếp hạng</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-clock-o">   Lịch sử thi đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-book">   Hướng dẫn</i>
      <% end %>
    </li>
  </ul>
  <ul class="top-nav pull-right">
    <li class="user-avatar">
      <%= image_tag "avatar.jpg"%>
    </li>
    <li>Tran Duc Thang</li>
  </ul>
</div>

<div class="container">
  <div class="row">
    <div class="content-exam row">
      <div class="time-exam">
        <div class="time-exam-lock">
          <i class="fa fa-clock-o"></i>
        </div>
      </div>
      <div class="image-exam">
        <%= image_tag "question.png" %>
      </div>
      <div class="question-exam">
        <span>Huyền có 20 bút chì màu, biết Huyền đã làm mất 4 chiếc bút chì màu. Số bút chì màu còn lại Huyền chia đều cho 2 em. Hỏi mỗi em có bao nhiêu bút chì màu?</span>
      </div>
      <div class="answer-exam">
        <div class="answer-exam-left">
          <div class="pointer"><span>5 Bút chì màu</span></div>
          <div class="pointer"><span>6 Bút chì màu</span></div>
        </div>
        <div class="answer-exam-right">
          <div class="pointer-two"><span>7 Bút chì màu</span></div>
          <div class="pointer-two"><span>8 Bút chì màu</span></div>
        </div>
      </div>
      <div class="totoal-question-exam">
        <span>6/10</span>
      </div>
    </div>
    <div class="rank row">
      <div class="top-nav-rank">
        <span>BẢNG XẾP HẠNG</span>
      </div>
      <div class="content-rank">
        <div class="play-rank">
          <span><b>1-</b> Tran Duc Thang  <b>(1996)</b></span>
        </div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
        <div class="play-rank"></div>
      </div>
      <div class="footer-rank">

      </div>
    </div>
  </div>
</div>

app/views/shared/_login_form.html.erb
<div class="form">
  <div class="thumbnail"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/169963/hat.svg"/></div>
  <form class="register-form">
    <input type="text" placeholder="name"/>
    <input type="password" placeholder="password"/>
    <input type="text" placeholder="email address"/>
    <button>create</button>
    <p class="message-sigin">Already registered? Sign In</p>
  </form>
  <form class="login-form">
    <input type="text" placeholder="username"/>
    <input type="password" placeholder="password"/>
    <button>login</button>
    <p class="message-sigup">Not registered? Create an account</p>
  </form>
</div>

app/views/shared/_waiting_room.html.erb
<div class="header">
  <ul class="top-nav">
    <li class="logo-top-nav">
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-users">  Tìm phòng đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-graduation-cap">   Bảng xếp hạng</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-clock-o">   Lịch sử thi đấu</i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fa fa-book">   Hướng dẫn</i>
      <% end %>
    </li>
  </ul>
  <ul class="top-nav pull-right">
    <li class="user-avatar">
      <%= image_tag "avatar.jpg"%>
    </li>
    <li>Tran Duc Thang</li>
  </ul>
</div>

<div class="container">
  <div class="top-nav-content">
    <ul class="title-list-room">
      <li>PHÒNG ĐẤU SỐ 1 (1 VS 9)</li>
    </ul>
  </div>
  <div class="content row">
    <div class="list-room waiting-room">
      <div class="list-btn-inroom">
        <div class="total-player-room">
          <span>Số người chờ 10/10</span>
        </div>
        <div class="close-room">
          <button class="btn btn-danger">Rời phòng</button>
        </div>
        <div class="start-room">
          <button class="btn btn-success">Sẵn sàng</button>
        </div>
      </div>
      <div class="player-inroom">
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
          <div class="text-center"><strong>Tran Duc Thang</strong></div>
          <div class="user-win"><span>1996</span></div>
          <div class="text-center"><span>TRẬN THẮNG</span></div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
        <div class="player">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
        </div>
      </div>
    </div>
    <div class="chat">
      <div class="top-nav-chat">
        <span>Nhắn tin</span>
      </div>
      <div class="content-chat">

      </div>
      <div class="footer-chart">

      </div>
    </div>
  </div>
</div>