config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"

  resources :relationships
  resources :rooms do
    member do
      resource :exames
      post 'start', to: "exames#start_game"
      get 'result', to: "exames#result"
      get :unfollow
    end
    resource :answers
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :users, through: :user_rooms

  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.destroy(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsHelper
  before_action :check_show_roo, only: :show
  before_action :make_exame, only: :create

  def index
    @rooms = Room.all
  end

  def show
    if get_relationship_id(current_user).status.nil?
      get_relationship_id(current_user).update status: 0
    end
  end

  def new
    if Relationship.pluck(:followed_id).include? current_user.id
      flash[:danger] = "Ban Dang Thi dau nen khong the tao phong."
      redirect_to root_path
    else
      @room = Room.new
    end
  end

  def create
    @room = current_user.rooms.new room_params.merge(exame_id: @exame.id)
    @room.owner = current_user.id
    if @room.save
      redirect_to @room
    else
      render :new
    end
  end

  def unfollow
    room = Room.find_by id: params[:id]
    if room.following? current_user
      room.unfollow current_user
      if current_user.id == room.owner && room.following.size > 1
        room.update_attributes owner: room.following.first.id
      end
      redirect_to root_path
    end
  end

  def destroy
    @room = Room.find_by id: params[:id]
    @room.destroy if @room.following.size == 1
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit :user_quantity, :class_room_id, :subject_id, :name
  end

  def check_show_roo
    @room = Room.find_by id: params[:id]
    return redirect_to root_path unless @room
    if (@room.following.size == @room.user_quantity) || (Relationship.pluck(:followed_id).include? current_user.id)
      return if @room.following? current_user
      flash[:danger] = "Phòng đã đủ người."
      redirect_to root_path
    else
      follow_room
    end
  end

  def follow_room
    if !@room.following? current_user
      @room.follow current_user
    end
  end

  def make_exame
    @exame = Exame.offset(rand(Exame.count)).last if Exame.present?
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def owner_room id
    User.find_by(id: id).name if id
  end

  def kind_room quantity_room
    quantity_room == 1 ? "Doi Khang" : "Tap The"
  end

  def class_room_name id
    ClassRoom.find_by(id: id).name
  end

  def subject_name id
    Subject.find_by(id: id).name
  end

  def status_room room
    "#{room.following.size}/#{room.user_quantity}"
  end

  def get_relationship_id user
    Relationship.find_by followed_id: user
  end
end

app/views/rooms/_status_user_in_room.html.erb
<% if room.owner != current_user.id %>
  <% if get_relationship_id(current_user).status == 0 %>
    <button class="btn btn-success follow follow-un" data-relation-id="<%= get_relationship_id(current_user).id %>">Sẵn sàng</button>
  <% else %>
    <button class="btn btn-success unfollow follow-un" data-relation-id="<%= get_relationship_id(current_user).id %>">Không sẵn sàng</button>
  <% end %>
<% else %>
  <button class="btn btn-success start-game" data-room="<%= room.id %>">
    Bắt đầu
  </button>
<% end %>

app/views/rooms/index.html.erb
<div class="container">
<div class="top-nav-content">
  <ul class="title-list-room">
    <li>DANH SÁCH PHÒNG THI ĐẤU</li>
    <li class="pull-right">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        <i class="fa fa-user-plus">  Tạo Phòng</i>
      <% end %>
    </li>
  </ul>
</div>
<div class="content row">
  <div class="list-room">
    <div class="tab">
      <button class="tablinks" onclick="openTabs('all-room')">Tất cả</button>
      <button class="tablinks" onclick="openTabs('room-1-vs-1')">1 vs 1</button>
      <button class="tablinks" onclick="openTabs('room-1-vs-9')">1 vs 9</button>
      <div class="form-group col-md-3">
        <select class="form-control" id="sel1">
          <option>Tất cả các lớp</option>
          <option>Lớp 1</option>
          <option>Lớp 2</option>
          <option>Lớp 3</option>
        </select>
      </div>
      <div class="search-room col-md-3">
        <input type="text" class="search" placeholder="Search for names..">
      </div>
    </div>

    <div id="all-room" class="tabcontent" style="display: block;">
      <table class="table table-bordered">
        <thead>
          <th>Số</th>
          <th>Chủ phòng</th>
          <th>Tên phòng</th>
          <th>Loại phòng</th>
          <th>Môn</th>
          <th>Lớp</th>
          <th>Trạng thái</th>
        </thead>
        <tbody>
          <% if @rooms.empty? %>
            <tr>
              <th colspan="7" class="text-center">Khong co phong.</th>
            </tr>
          <% else %>
            <% @rooms.each do |room| %>
              <tr>
                <th scope="row"><%= room.id %></th>
                <td><%= owner_room room.owner %></td>
                <td>
                  <%= link_to room.name, room_path(room) %>
                </td>
                <td><%= kind_room room.user_quantity %></td>
                <td><%= subject_name room.subject_id %></td>
                <td><%= class_room_name room.class_room_id %></td>
                <td><%= status_room room %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

    <div id="room-1-vs-1" class="tabcontent">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Số</th>
            <th>Chủ phòng</th>
            <th>Tên phòng</th>
            <th>Loại phòng</th>
            <th>Số người</th>
            <th>Trạng thái</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
            <td>@mdo</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@TwBootstrap</td>
            <td>@TwBootstrap</td>
            <td>@TwBootstrap</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            <td>@fat</td>
            <td>@fat</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div id="room-1-vs-9" class="tabcontent">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Số</th>
            <th>Chủ phòng</th>
            <th>Tên phòng</th>
            <th>Loại phòng</th>
            <th>Môn</th>
            <th>Số người</th>
            <th>Trạng thái</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>Đấu tập thể</td>
            <td>@mdo</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>Đôi kháng</td>
            <td>@TwBootstrap</td>
            <td>@TwBootstrap</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            <td>@fat</td>
            <td>@fat</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="chat">
    <div class="top-nav-chat">
      <span>Chat All</span>
    </div>
    <div class="content-chat">

    </div>
    <div class="footer-chart">

    </div>
  </div>
</div>
</div>

app/views/rooms/new.html.erb
<div class="container">
<div class="top-nav-content">
  <ul class="title-list-room">
    <li>TẠO PHÒNG THI ĐẤU</li>
    <li class="pull-right">
      <%= link_to root_path, class: "btn btn-primary" do %>
        <i class="fa fa-user-plus">Thi Đấu</i>
      <% end %>
    </li>
  </ul>
</div>
<div class="content row">
  <div class="list-room">
    <%= form_for @room do |f| %>
      <div class="notice-new-room">
        <span>Tạo phòng đấu mới bằng cách chọn hình thức thi đấu và khẩu hiệu phòng (có thể bỏ qua)</span>
      </div>
      <div class="new-room">
        <div class="kind-room">
          <span>CHỌN HÌNH THỨC THI ĐẤU</span>
          <div class="kind_play">
           Đối kháng (1 vs 1)<br>
            <%= f.radio_button :user_quantity, '2', :checked => true %>
           &nbsp;&nbsp; &nbsp;Đấu với 1 người chơi khác
          </div>
          <div class="kind_play">
            Đấu tập thể (1 vs 9)<br>
            <%= f.radio_button :user_quantity, '10' %>
           &nbsp;&nbsp;&nbsp; Đấu với 9 người chơi khác
          </div>
          <div class="row class-subject">
            <div class="form-group col-md-5">
              <%= f.select :class_room_id, options_for_select(ClassRoom.all.map{|x| [x.name, x.id]}),{}, class: "form-control" %>
            </div>
            <div class="form-group col-md-6">
              <%= f.select :subject_id, options_for_select(ClassRoom.last.subjects.map{|x| [x.name, x.id]}),{}, class: "form-control" %>
            </div>
            <div class="form-group col-md-11">
              <%= f.text_field :name, placeholder: "Enter name room..", class: "form-control" %>
            </div>
          </div>
          <div class="form-group lock-room">
            <input type="checkbox" name="">
            &nbsp;&nbsp;<span>Phòng thi đấu riêng</span>
            <i class="fa fa-lock" aria-hidden="true"></i>
          </div>
          <div class="footer-new-room">
            <div class="btn-new-room">
              <button class="btn btn-success">Tạo phòng</button>
            </div>
            <div class="btn-close-room">
              <%= link_to "Thoát", root_path, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="chat">
    <div class="top-nav-chat">
      <span>Nhắn tin</span>
    </div>
    <div class="content-chat">

    </div>
    <div class="footer-chart">

    </div>
  </div>
</div>
</div>

app/views/rooms/show.html.erb
<div class="container">
<div class="top-nav-content">
  <ul class="title-list-room">
    <li>PHÒNG ĐẤU SỐ 1 (1 VS 9)</li>
  </ul>
</div>
<div class="content row">
  <div class="list-room waiting-room">
    <div class="list-btn-inroom">
      <div class="total-player-room">
        <span>Số người chờ <%= @room.following.count %>/<%= @room.user_quantity %></span>
      </div>
      <div class="close-room">
        <% if @room.following.size == 1 %>
          <%= link_to "Rời phòng", room_path(@room), method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Rời phòng",unfollow_room_path, class: "btn btn-danger" %>
        <% end %>
      </div>
      <div class="start-room">
        <%= render partial: "status_user_in_room", locals: {room: @room} %>
      </div>
    </div>
    <div class="player-inroom">
      <% @room.following.order(:created_at).each do |user| %>
        <div class="player status_user_in_room-<%= user.id %>" id= "user-<%= user.id %>">
          <div class="image-player">
            <%= image_tag "avatar.jpg" %>
          </div>
          <div class="text-center name-user"><strong><%= user.name %></strong></div>
          <div class="user-win"><span><%= user.victory %></span></div>
          <div class="text-center"><span>TRẬN THẮNG</span></div>
          <% if (@room.owner != user.id) && (get_relationship_id(user).status == 1) %>
            <div class="parent-user-ready" style="height: 21px">
              <div class="user-ready"><span>Sẵn sàng</span></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="chat">
    <div class="top-nav-chat">
      <span>Nhắn tin</span>
    </div>
    <div class="content-chat">

    </div>
    <div class="footer-chart">

    </div>
  </div>
</div>
</div>